# -------------------------
# CONFIG

# Js Config
driver:
  name: dataTables
  conf:
    itemName: client
    itemsName: clients
    # masculin ou féminin
    # "e"|""
    itemGenre:
    requestUrl: data.json
    requestMethod: POST
    dom: <"H"TClfr>t<"F"ip>
    defaultSort:
    - [0, asc]

source:
  name: doctrine
  conf:
    select:
      - c.societe
      - c.civilite
      - c.nom
      - c.prenom
      - c.email
      - c.time_inscription
      - a.tel1 tel
      - IF(c.ns > 0, "Oui", "Non") AS offre
      - CONCAT(a.adresse1, "<br>", IF(a.adresse2 IS NULL, "", a.adresse2), "<br>", a.cp, " ", a.ville, "<br>", a.pays) AS adresse

    from:
      name: client
      alias: c

    innerJoin:
      -
        name: client_adresse
        alias: a
        on: a.client_id = c.id AND a.principal = 1

    group: c.id


## COLUMNS

columns:
#  columnName:
#    label: columnLabel
#    filter: 1|0
#    sort: 1|0
#    source: source expression (for example a column)
#    ...

  societe:
    label: Société
    filter: 1
    sort: 1
    source: c.societe
  email:
    label: Email
    filter: 1
    sort: 1
    source: c.email
  tel:
    label: Téléphone
    filter: 1
    sort: 1
    source: a.tel1
  nom:
    label: Nom
    filter: 1
    sort: 1
    source: c.nom
  prenom:
    label: Prénom
    filter: 1
    sort: 1
    source: c.prenom
  offre:
    label: Offre
    filter: 0
    sort: 1
    source: offre
  adresse:
    label: Adresse
    filter: 0
    sort: 0
    callback: strip_tags
  time_inscription:
    label: Date
    filter: false
    sort: false
    callback:
      name: Solire\Trieur\Example\Format::sqlTo
      cell: 0
      arguments:
        - d/m/Y H:i:s
