# -------------------------
# CONFIG

# Js Config
driver:
  name: dataTables
  conf:
    itemName: client
    itemsName: clients
    # masculin ou féminin
    # "e"|""
    itemGenre:
    requestUrl: http://localhost/trieur/example/dataTables/doctrine/data.json
    requestMethod: POST
    dom: <"H"TClfr>t<"F"ip>
    defaultSort:
    - [0, asc]

connection:
  name: doctrine
  conf:
    select:
      - c.societe
      - c.civilite
      - c.nom
      - c.prenom
      - c.email
      - a.tel1 tel
      - IF(c.ns > 0, "Oui", "Non") AS offre
      - CONCAT(a.adresse1, "<br>", IF(a.adresse2 IS NULL, "", a.adresse2), "<br>", a.cp, " ", a.ville, "<br>", a.pays) AS adresse

    from:
      name: client
      alias: c

    innerJoin:
      -
        name: client_adresse
        alias: a
        on: a.client_id = c.id AND a.principal = 1

    group: c.id


## COLUMNS

columns:
#  columnName:
#    label: columnLabel
#    filter: 1|0
#    sort: 1|0
#    connection: connection expression (for example a column)
#    ...

  societe:
    label: Société
    filter: 1
    sort: 1
    connection: c.societe
  email:
    label: Email
    filter: true
    sort: true
    connection: c.email
  tel:
    label: Téléphone
    filter: true
    sort: true
    connection: a.tel1
  nom:
    label: Nom
    filter: true
    sort: true
    connection: c.nom
  prenom:
    label: Prénom
    filter: true
    sort: true
    connection: c.prenom
  offre:
    label: Offre
    filter: false
    sort: true
    connection: offre
  adresse:
    label: Adresse
    filter: false
    sort: false
