# -------------------------
# CONFIG

# Js Config
driver:
  name: csv
  conf:
    test: test

source:
  name: doctrine
  conf:
    select:
      - c.societe
      - c.civilite
      - c.nom
      - c.prenom
      - c.email
      - a.tel1 tel
      - IF(c.ns > 0, "Oui", "Non") AS offre
      - CONCAT(a.adresse1, "\n", IF(a.adresse2 IS NULL, "", a.adresse2), "\n", a.cp, " ", a.ville, "\n", a.pays) AS adresse

    from:
      name: client
      alias: c

    innerJoin:
      -
        name: client_adresse
        alias: a
        on: a.client_id = c.id AND a.principal = 1

    group: c.id


## COLUMNS

columns:
#  columnName:
#    label: columnLabel
#    sort: 1|0
#    filter: 1|0
#    filterType: text, dateRange...
#    source: source expression (for example a column)
#    sourceFilter: source expression (for example a column)
#    sourceSort: source expression (for example a column)
#    ...

  societe:
    label: Société
    filter: 1
    sort: 1
    source: c.societe
  email:
    label: Email
    filter: 1
    sort: 1
    source: c.email
  tel:
    label: Téléphone
    filter: 1
    sort: 1
    source: a.tel1
  nom:
    label: Nom
    filter: 1
    sort: 1
    source: c.nom
  prenom:
    label: Prénom
    filter: 1
    sort: 1
    source: c.prenom
  offre:
    label: Offre
    filter: 0
    sort: 1
    source: offre
  adresse:
    label: Adresse
    filter: 0
    sort: 0
