# -------------------------
# CONFIG

# Js Config
driver:
  name: dataTables
  conf:
    itemName: client
    itemsName: clients
    # masculin ou féminin
    # "e"|""
    itemGenre:
    requestUrl: http://localhost/trieur/example/dataTables/csv/data.json
    requestMethod: POST
    dom: <"H"TClfr>t<"F"ip>
    defaultSort:
    - [0, ASC]

connection:
  name: csv
  conf:
    test: test

## COLUMNS

columns:
#  columnName:
#    label: columnLabel
#    filter: 1|0
#    sort: 1|0
#    connection: connection expression (for example a column)
#    ...

  societe:
    label: Société
    filter: 1
    sort: 1
    connection: 0
  email:
    label: Email
    filter: true
    sort: true
    connection: 4
  tel:
    label: Téléphone
    filter: true
    sort: true
    connection: 5
  nom:
    label: Nom
    filter: true
    sort: true
    connection: 2
  prenom:
    label: Prénom
    filter: true
    sort: true
    connection: 3
  offre:
    label: Offre
    filter: false
    sort: true
    connection: 6
  adresse:
    label: Adresse
    filter: false
    sort: false
    connection: 7
