# -------------------------
# CONFIG

# Js Config
driver:
  name: dataTables
  conf:
    itemName: client
    itemsName: clients
    # masculin ou féminin
    # "e"|""
    itemGenre:
    requestUrl: data.json
    requestMethod: POST
    dom: <"H"TClfr>t<"F"ip>
    defaultSort:
    - [0, ASC]

source:
  name: csv
  conf:
    test: test

## COLUMNS

columns:
#  columnName:
#    label: columnLabel
#    filter: 1|0
#    sort: 1|0
#    source: source expression (for example a column)
#    ...

  societe:
    label: Société
    filter: 1
    sort: 1
    source: 0
  email:
    label: Email
    filter: 1
    sort: 1
    source: 4
  tel:
    label: Téléphone
    filter: 1
    sort: 1
    source: 5
  nom:
    label: Nom
    filter: 1
    sort: 1
    source: 2
  prenom:
    label: Prénom
    filter: 1
    sort: 1
    source: 3
  offre:
    label: Offre
    filter: 0
    sort: 1
    source: 6
  adresse:
    label: Adresse
    filter: 0
    sort: 0
    source: 7
